# .air.toml

root = "."
tmp_dir = "tmp"

[build]
# ToDo: Swagger not work
pre_cmd = ["swag init -dir ./cmd/app"]

bin = "./tmp/main"
cmd = "go build -o ./tmp/main ./cmd/app/main.go"

# ไดเรกทอรีที่ Air ควรจะตรวจสอบการเปลี่ยนแปลง
include_dir = ["cmd", "config", "internal"]
# ไดเรกทอรีที่ Air ไม่ควรตรวจสอบการเปลี่ยนแปลง
exclude_dir = ["tmp", "vendor", "docs"]
include_ext = ["go", "tpl", "tmpl", "html", "yaml", "json"]

[run]
cmd = "./tmp/main"

[log]
time = true

[color]
app = ""
build = "yellow"
main = "magenta"
watcher = "cyan"

[misc]
clean_on_exit = true
